variables:
  IMAGE_PATH: qa
  IMAGE_NAME: ${CI_PROJECT_NAME}

include:
  - project: bbc/devops/gitlab-pipeline/cicd-pipeline
    ref: master
    file: 'qa-automaion-pipeline.yml'
    rules:
      - if: ($CI_COMMIT_BRANCH =~ /master/ || CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /master/)
  - project: bbc/devops/gitlab-pipeline/cicd-pipeline
    ref: master
    file: 'qa-manual-test.yml'
    rules:
      - if: ($CI_COMMIT_BRANCH =~ /main/ || CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /main/)