variables:
  IMAGE_PATH: qa
  IMAGE_NAME: ${CI_PROJECT_NAME}

include:
  stage: test1
  project: bbc/devops/gitlab-pipeline/cicd-pipeline
  ref: master
  file: 'qa-automaion-pipeline.yml'

test:
  script:
    - env





# variables:
#   IMAGE_PATH: qa
#   IMAGE_NAME: ${CI_PROJECT_NAME}

# include:
#   project: bbc/devops/gitlab-pipeline/cicd-pipeline
#   ref: master
#   file: 'qa-automaion-pipeline.yml'
