variables:
  IMAGE_PATH: qa
  IMAGE_NAME: ${CI_PROJECT_NAME}
  FILE_NAME: 'qa-automaion-pipeline.yml'

include:
  - project: nld/devops/3.0/cicd/pipeline-yaml
    ref: main
    file: scripts/ci/qa-team/${FILE_NAME}
    rules:
      - if: $CI_COMMIT_REF_NAME =~ "refs/heads/master"