variables:
  IMAGE_PATH: qa
  IMAGE_NAME: ${CI_PROJECT_NAME}

only:
  - master
  include:
    - project: bbc/devops/gitlab-pipeline/cicd-pipeline
      ref: master
      file: 'qa-automaion-pipeline.yml'
     
only:
  - main
  include:
    - project: bbc/devops/gitlab-pipeline/cicd-pipeline
      ref: master
      file: 'qa-manual-test.yml'