variables:
  IMAGE_PATH: qa
  IMAGE_NAME: ${CI_PROJECT_NAME}

stages: 
  - pre

include:
  - project: bbc/devops/gitlab-pipeline/cicd-pipeline
    ref: master
    file: 'qa-automaion-pipeline.yml'
    rules:
      - if: $CI_COMMIT_BRANCH == "master"
  - project: bbc/devops/gitlab-pipeline/cicd-pipeline
    ref: master
    file: 'qa-manual-test.yml'

test:
  stage: pre
  script:
    - env